#!/bin/sh
set -u
set -e

usage() {
  echo "Runs a command across multiple crankctl"
  echo
  echo "Usage: crankall <prefix> [crank opts]"
}

prefix=$1
shift
if [ -z "$prefix" ]; then
  usage
  exit 1
fi

if [ "$prefix" = "-h" ] || [ "$prefix" = "--help" ]; then
  usage
  exit
fi

if ! echo "$prefix" | grep -q '^[/.]' ; then
  prefix="/var/run/crank/$prefix"
fi

for ctl in $(ls $prefix*.ctl | sort) ; do
  name=`basename $ctl | sed 's/.ctl$//'`
  echo "For $name"
  crankctl -ctl $ctl "$@"
done

